spring.application.name=LarzCode
spring.datasource.url=jdbc:mysql://localhost:3307/larzycodedb
spring.datasource.username=larzy
spring.datasource.password=Yato1141_111
spring.jpa.hibernate.ddl-auto=create
spring.jpa.properties.hibernate.format_sql=true

